name: Assign PR reviewer if not already assigned
on:
  - pull_request_review

jobs:
  assign-pr-reviewer-if-missing:
    name: Check & assign
    if: github.event.pull_request.assignee == null && github.event.pull_request.user.login != github.event.sender.login
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
    steps:
      - uses: actions/checkout@v3
      - run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ github.event.sender.login }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
